make :
	javac EdmondsKarp.java FlowData.java

run :
	java EdmondsKarp FlowData g1.txt

run2 :
	java EdmondsKarp FlowData g2.txt

run3 :
	java EdmondsKarp FlowData g100.txt

clean :
	$(RM) *~ , *.class
